language: cpp

compiler:
  - clang

before_install:
  - sudo add-apt-repository -y ppa:george-edison55/precise-backports
  - sudo apt-get update -qq

install:
  - sudo apt-get install cmake cmake-data libgtest-dev
  - mkdir gtest_build
  - cd gtest_build
  - cmake /usr/src/gtest
  - make
  - sudo mv libg* /usr/lib
  - cd -

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ctest
