language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:george-edison55/precise-backports
  - sudo apt-get update -qq

install:
  - sudo apt-get install cmake cmake-data libgtest-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ctest
